## XBRL US API - Python example  
This sample Python code queries the XBRL US Public Filings Database.
### Authenticate for access token 
Run the cell below, then type your XBRL US Web account email, account password, Client ID, and secret (get these from https://xbrl.us/access-token), pressing the Enter key on the keyboard after each entry.

XBRL US limits records returned for a query to improve efficiency; this script loops to collect all data from the Public Filings Database for a query. **Non-members might not be able to return any or all data for a query** - join XBRL US for comprehensive access - https://xbrl.us/join.

In [ ]:
print('Enter your XBRL US Web account email: ')
import os, re, sys, json
import requests
import pandas as pd
from IPython.display import display, HTML
import numpy as np
import getpass
from datetime import datetime
import urllib
from urllib.parse import urlencode
email = input()
password = getpass.getpass(prompt='Password: ')
clientid = getpass.getpass(prompt='Client ID: ')
secret = getpass.getpass(prompt='Secret: ')

body_auth = {'username' : ''.join(email), 
            'client_id': ''.join(clientid), 
            'client_secret' : ''.join(secret), 
            'password' : ''.join(password), 
            'grant_type' : 'password', 
            'platform' : 'ipynb' }

payload = urlencode(body_auth)
url = 'https://api.xbrl.us/oauth2/token'
headers = {"Content-Type": "application/x-www-form-urlencoded"}

res = requests.request("POST", url, data=payload, headers=headers)
auth_json = res.json()

if 'error' in auth_json:
    print ("\n\nThere was a problem generating an access token with these credentials. Run the first cell again to enter credentials.")
else:
    print ("\n\nYour access token expires in 60 minutes. After it expires, run the cell immediately below this one to generate a new token and continue to use the query cell. \n\nFor now, skip ahead to the section 'Make a Query'.")
access_token = auth_json['access_token']
refresh_token = auth_json['refresh_token']
newaccess = ''
newrefresh = ''
#print('access token: ' + access_token + ' refresh token: ' + refresh_token)

#### Refresh token 
The cell below is only needed to refresh an expired access token after 60 minutes. When the access token no longer returns results, run the cell below to refresh the access token or re-enter credentials by running the cell above. Until the refresh token process is needed, skip ahead to **Make a Query**.

In [ ]:
token = token if newrefresh != '' else refresh_token 

refresh_auth = {'client_id': ''.join(clientid), 
            'client_secret' : ''.join(secret), 
            'grant_type' : 'refresh_token', 
            'platform' : 'ipynb', 
            'refresh_token' : ''.join(token) }
refreshres = requests.post(url, data=refresh_auth)
refresh_json = refreshres.json()
access_token = refresh_json['access_token']
refresh_token = refresh_json['refresh_token']#print('access token: ' + access_token + 'refresh token: ' + refresh_token)
print('Your access token is refreshed for 60 minutes. If it expires again, run this cell to generate a new token and continue to use the query cells below.')
print(access_token)

### Make a query 
After the access token confirmation appears above, you can modify the query below, then use the **_Cell >> Run_** menu option from the cell **immediately below this text** to run the entire query for results.

There are two searches in separate routines below - the first identifies dts.id values for Apple 10-Ks and the second uses the hard-coded values in a query to return any instance of the defined text string pattern in the entire document - this search is restricted to XBRL US Member accounts.
  
Refer to XBRL API documentation at https://xbrlus.github.io/xbrl-api/ for other endpoints and parameters to filter and return.

In [ ]:
# Define the parameters for the filter and fields to be returned, 
# run the loop to return results 
# Use any of these singly: 
# fact | dts | entity | network | relationship etc. 
# see https://xbrlus.github.io/xbrl-api for appropriate 
# search parameters and fields for each endpoint.

endpoint = 'report'
offset_value = 0
res_df = []

# Define the parameters of the query

sic_code = [3571
           ] 

reports = ['10-K',
           '10-K/A'
        ]

# OR search by company (comment out SIC code in param) 

companies_cik = [#'0000320193', ## Apple (AAPL)
                ]

# Define data fields to return (multi-sort based on order)

fields = ['report.filing-date.sort(DESC)',
          'report.entity-name',
          'report.document-type',
          'dts.id'
         ]

string_years = [str(int) for int in years]
string_sic = [str(int) for int in sic_code]

params = {'report.sic-code': ','.join(string_sic),
         'report.document-type': ','.join(reports),
         #'entity.cik': ','.join(companies_cik),
         'fields': ','.join(fields)
         }

# Execute the query with loop for all results

search_endpoint = 'https://api.xbrl.us/api/v1/'+endpoint+'/search'
orig_fields = params['fields']

count = 0
query_start = datetime.now()
printed = False
while True:
    if not printed:
        print("On", query_start.strftime("%c"), email, "(client ID:", str(clientid.split('-')[0]), "...) started the query and")
        printed = True
    res = requests.get(search_endpoint, params=params, headers={'Authorization' : 'Bearer {}'.format(access_token)})
    res_json = res.json()
    if 'error' in res_json:
        print('There was an error: {}'.format(res_json['error_description']))
        break

    print("up to", str(offset_value + res_json['paging']['limit']), "records are found so far ...")

    res_df += res_json['data']

    if res_json['paging']['count'] < res_json['paging']['limit']:
        print(" - this set contained fewer than the", res_json['paging']['limit'], "possible, only", str(res_json['paging']['count']), "records.")
        break
    else: 
        offset_value += res_json['paging']['limit'] 
        if 100 == res_json['paging']['limit']:
                params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)
                if offset_value == 10 * res_json['paging']['limit']:
                        break 
        elif 500 == res_json['paging']['limit']:
                params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)
                if offset_value == 4 * res_json['paging']['limit']:
                        break 
        params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)

if not 'error' in res_json:
    current_datetime = datetime.now().replace(microsecond=0)
    time_taken = current_datetime - query_start
    index = pd.DataFrame(res_df).index
    total_rows = len(index)
    your_limit = res_json['paging']['limit']
    limit_message = "If the results below match the limit noted above, you might not be seeing all rows, and should consider upgrading (https://xbrl.us/access-token).\n"
    
    if your_limit == 100:
        print("\nThis non-Member account has a limit of " , 10 * your_limit, " rows per query from our Public Filings Database. " + limit_message)
    elif your_limit == 500:
        print("\nThis Basic Individual Member account has a limit of ", 4 * your_limit, " rows per query from our Public Filings Database. " + limit_message)
    
    print("\nAt " + current_datetime.strftime("%c") +  ", the query finished with  ", str(total_rows), "  rows returned in " + str(time_taken) + " for \n" +  urllib.parse.unquote(res.url))
    
    
    # the format truncates the HTML display of numerical values to two decimals; .csv data is unaffected
    pd.options.display.float_format = '{:,.2f}'.format
    display(HTML(pd.DataFrame(res_df).to_html()))

On Mon Jan 17 13:55:13 2022 //email// (client ID: 9d3618e3 ...) started the query and
up to 2000 records are found so far ...
 - this set contained fewer than the 2000 possible, only 102 records.

At Mon Jan 17 13:55:13 2022, the query finished with   102   rows returned in -1 day, 23:59:59.938799 for
https://api.xbrl.us/api/v1/report/search?report.sic-code=3571&report.document-type=10-K,10-K/A&fields=report.filing-date.sort(DESC),report.entity-name,report.document-type,dts.id

In [ ]:
# Define the parameters for the filter and fields to be returned, 
# run the loop to return results 
# Use any of these singly: 
# fact | dts | entity | network | relationship etc. 
# see https://xbrlus.github.io/xbrl-api for appropriate 
# search parameters and fields for each endpoint.

endpoint = 'document' #Use any of these singly: fact | dts | entity | network | relationship etc. - see https://xbrlus.github.io/xbrl-api for appropriate search parameters and fields for each endpoint
offset_value = 0
res_df = []

# Define the parameters of the query 

text_search = ['21.1 NEAR/2 subsidiaries' 
                ]

# Define data fields to return (multi-sort based on order)

fields = [ 'document-type',
           'document.uri',
           'dts.id.sort(DESC)',
           'document.example'
         ]

params = { 'dts.id': '505653,493972,450469,450164,449583,441926,418604,412227,410430,374761,374483,374568,368136,367772,359056',
         'document.text-search': ','.join(text_search),
         'fields': ','.join(fields)
         }

# Execute the query with loop for all results

search_endpoint = 'https://api.xbrl.us/api/v1/'+endpoint+'/search'
orig_fields = params['fields']

count = 0
query_start = datetime.now()
printed = False
while True:
    if not printed:
        print("On", query_start.strftime("%c"), email, "(client ID:", str(clientid.split('-')[0]), "...) started the query and")
        printed = True
    res = requests.get(search_endpoint, params=params, headers={'Authorization' : 'Bearer {}'.format(access_token)})
    res_json = res.json()
    if 'error' in res_json:
        print('There was an error: {}'.format(res_json['error_description']))
        break

    print("up to", str(offset_value + res_json['paging']['limit']), "records are found so far ...")

    res_df += res_json['data']

    if res_json['paging']['count'] < res_json['paging']['limit']:
        print(" - this set contained fewer than the", res_json['paging']['limit'], "possible, only", str(res_json['paging']['count']), "records.")
        break
    else: 
        offset_value += res_json['paging']['limit'] 
        if 100 == res_json['paging']['limit']:
                params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)
                if offset_value == 10 * res_json['paging']['limit']:
                        break 
        elif 500 == res_json['paging']['limit']:
                params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)
                if offset_value == 4 * res_json['paging']['limit']:
                        break 
        params['fields'] = orig_fields + ',' + endpoint + '.offset({})'.format(offset_value)

if not 'error' in res_json:
    current_datetime = datetime.now().replace(microsecond=0)
    time_taken = current_datetime - query_start
    index = pd.DataFrame(res_df).index
    total_rows = len(index)
    your_limit = res_json['paging']['limit']
    limit_message = "If the results below match the limit noted above, you might not be seeing all rows, and should consider upgrading (https://xbrl.us/access-token).\n"
    
    if your_limit == 100:
        print("\nThis non-Member account has a limit of " , 10 * your_limit, " rows per query from our Public Filings Database. " + limit_message)
    elif your_limit == 500:
        print("\nThis Basic Individual Member account has a limit of ", 4 * your_limit, " rows per query from our Public Filings Database. " + limit_message)
    
    print("\nAt " + current_datetime.strftime("%c") +  ", the query finished with  ", str(total_rows), "  rows returned in " + str(time_taken) + " for \n" +  urllib.parse.unquote(res.url))
    
    
    # the format truncates the HTML display of numerical values to two decimals; .csv data is unaffected
    pd.options.display.float_format = '{:,.2f}'.format
    display(HTML(pd.DataFrame(res_df).to_html()))

On Mon Jan 17 14:01:59 2022 //email// (client ID: 9d3618e3 ...) started the query and
up to 2000 records are found so far ...
 - this set contained fewer than the 2000 possible, only 8 records.

At Mon Jan 17 14:02:04 2022, the query finished with   8   rows returned in 0:00:04.205868 for
https://api.xbrl.us/api/v1/document/search?dts.id=505653,493972,450469,450164,449583,441926,418604,412227,410430,374761,374483,374568,368136,367772,359056&document.text-search=21.1+NEAR/2+subsidiaries&fields=document-type,document.uri,dts.id.sort(DESC),document.example

In [ ]:
# If you run this program locally, you can save the output to a file 
# on your computer (modify D:\results.csv to your system)

df = pd.DataFrame(res_df)
df.to_csv(r"D:\results.csv",sep=",")